#!/usr/bin/bash

wget https://dl.suckless.org/dwm/dwm-6.3.tar.gz

wget https://dl.suckless.org/tools/dmenu-5.1.tar.gz

wget https://dl.suckless.org/st/st-0.8.5.tar.gz

for i in *.gz do
    tar -zxvf $i
    rm -rf $i
done
