#!/bin/bash

clear

# Instalando o lightdm com slick-greeter
pacman -S lightdm
sleep 2s
pacman -S lightdm-gtk-greeter lightdm-slick-greeter
sleep 2s
systemctl enable lightdm.service
sleep 2s

# Apos criar o arquivo slick-greeter.conf, apague todo o conteudo do arquivo e deixe somente as linhas abaixo.

#sudo touch slick-greeter.conf
#sudo echo > "[Greeter]" /etc/lightdm/slick-greeter.conf
#sudo echo >> "background=/usr/share/backgrounds/archlinux/wallpaper.jpg" /etc/lightdm/slick-greeter.conf

# Execute este comando para ter uma previa do lightdm
#dm-tool switch-to-greeter

# As root create a file like this:
echo -e "${s}${b}Criando o diretorio xsessions...${f}"
sleep 2s
mkdir /usr/share/xsessions

echo -e "${s}${b}Criando o arquivo dwm.desktop...${f}"
sleep 2s
touch /usr/share/xsessions/dwm.desktop

echo -e "${s}${b}Injetando o conteudo no arquivo dwm.desktop...${f}"
sleep 2s
cat >> '/usr/share/xsessions/dwm.desktop' << EOF
[Desktop Entry]
Encoding=UTF-8
Name=dwm
Comment=Dynamic window manager
Exec=dwm
Icon=dwm
Type=XSession
EOF

echo -e "${s}${b}Listando o arquivo dwm.desktop...${f}"
echo
echo -e "${s}${b}O arquivo dwm.desktop deve estar igual a esse...${f}"
echo "-rw-r--r-- 1 root root 108 Jun 27 17:24 /usr/share/xsessions/dwm.desktop"
echo
ls -l /usr/share/xsessions/dwm.desktop
